vich_uploader:
    db_driver: orm

    mappings:
       brands:
           uri_prefix: /images/brands
           upload_destination: '%kernel.project_dir%/public/images/brands'
           namer: Vich\UploaderBundle\Naming\HashNamer