vich_uploader:
    db_driver: orm

    mappings:
       brands:
           uri_prefix: /images/brands
           upload_destination: '%kernel.project_dir%/public/images/brands'
           namer: Vich\UploaderBundle\Naming\HashNamer
       brandsCategory:
           uri_prefix: /images/brands/categories
           upload_destination: '%kernel.project_dir%/public/images/brands/categories'
           namer: Vich\UploaderBundle\Naming\HashNamer
       familyThumbnail:
           uri_prefix: /images/family
           upload_destination: '%kernel.project_dir%/public/images/family'
           namer: Vich\UploaderBundle\Naming\HashNamer
       family:
            uri_prefix: /data/familly
            upload_destination: '%kernel.project_dir%/public/data/familly'
            namer: Vich\UploaderBundle\Naming\HashNamer