vich_uploader:
    db_driver: orm

    mappings:
        Fabricant:
           uri_prefix: /images/Brands
           upload_destination: '%kernel.project_dir%/public/images/Brands'
           namer: Vich\UploaderBundle\Naming\HashNamer
        User:
           uri_prefix: /images/Users
           upload_destination: '%kernel.project_dir%/public/images/Users'
           namer: Vich\UploaderBundle\Naming\HashNamer
        Family:
           uri_prefix: /images/Families
           upload_destination: '%kernel.project_dir%/public/images/Families'
           namer: Vich\UploaderBundle\Naming\HashNamer